import { Sandbox } from "@e2b/code-interpreter"
import { Octokit } from "@octokit/rest"
import { getSupabaseAdmin } from "@/lib/supabase"
import { corsResponse, corsOptions } from "@/lib/cors"

export const maxDuration = 120

export function OPTIONS() { return corsOptions() }

// Files generated by package managers or env setup — not user edits.
// Filtered out so they don't pollute PRs (especially for sandboxes
// where git init ran before npm install).
const ARTIFACT_FILES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
])

function parseNameStatus(output: string): { status: string; file: string; oldFile?: string }[] {
  return output.trim().split("\n").filter(Boolean).map((line) => {
    const parts = line.split("\t")
    const status = parts[0].charAt(0)
    if (status === "R" || status === "C") {
      return { status, file: parts[2], oldFile: parts[1] }
    }
    return { status, file: parts[1] }
  })
}

export async function POST(req: Request) {
  let sandbox: Awaited<ReturnType<typeof Sandbox.connect>> | undefined
  try {
    const { sandboxId, scriptTagId, prompt, bountyAmount, userEmail } = await req.json()

    const { data: project } = await getSupabaseAdmin()
      .from("projects")
      .select("*, companies(github_token)")
      .eq("script_tag_id", scriptTagId)
      .single()

    if (!project) return corsResponse({ error: "Not found" }, { status: 404 })

    const githubToken = (project.companies as any).github_token
    if (!githubToken) {
      return corsResponse({ error: "GitHub token not configured" }, { status: 500 })
    }

    // Connect to the sandbox — most common failure point (sandbox expired/killed)
    try {
      sandbox = await Sandbox.connect(sandboxId)
    } catch (e) {
      console.error("[sandbox/submit] Failed to connect to sandbox:", e)
      return corsResponse(
        { error: "Sandbox expired or unavailable. Please reload the page and try again." },
        { status: 410 },
      )
    }

    // Quick health check — verify sandbox is responsive
    try {
      await sandbox.commands.run("echo ok", { timeoutMs: 5_000 })
    } catch (e) {
      console.error("[sandbox/submit] Sandbox health check failed:", e)
      return corsResponse(
        { error: "Sandbox is not responding. Please reload the page and try again." },
        { status: 410 },
      )
    }

    const [owner, repo] = project.repo_full_name.split("/")
    const branchName = `tweaky/${Date.now()}`
    const defaultBranch = project.default_branch || "main"

    // Detect app directory (same logic as create route — find where .git was initialized)
    let appDir = "/home/user/app"
    try {
      const gitDirCheck = await sandbox.commands.run(
        'git -C /home/user/app rev-parse --show-toplevel 2>/dev/null || find /home/user/app -maxdepth 2 -name .git -type d | head -1 | xargs dirname 2>/dev/null || echo /home/user/app',
        { timeoutMs: 5_000 },
      )
      appDir = (gitDirCheck.stdout || "").trim() || "/home/user/app"
    } catch { /* fallback to default */ }

    // Stage all changes and get name-status in one round-trip.
    // Note: commands.run throws CommandExitError on non-zero exit, so failures are caught.
    let changedEntries: { status: string; file: string; oldFile?: string }[]
    try {
      const result = await sandbox.commands.run(
        `cd ${appDir} && git add -A && git diff --cached --name-status HEAD`,
        { timeoutMs: 30_000 },
      )
      const allEntries = parseNameStatus(result.stdout)
      // Filter out package manager artifacts and env files
      changedEntries = allEntries.filter((e) => !ARTIFACT_FILES.has(e.file))
    } catch (e) {
      console.error("[sandbox/submit] Failed to detect changes:", e)
      return corsResponse({ error: "Failed to detect changes" }, { status: 500 })
    }

    if (changedEntries.length === 0) {
      return corsResponse({ error: "No changes to submit" }, { status: 400 })
    }

    // The sandbox has an unrelated git history (tarball → git init), so we can't
    // rebase or apply diffs. Strategy: archive changed files with tar, checkout a
    // fresh branch from origin, restore the files, commit, and push.
    const commitMessage = `[Tweaky] ${prompt}`
    try {
      // Build file lists for batch operations
      const filesToCopy = changedEntries.filter((e) => e.status !== "D").map((e) => e.file)
      const filesToDelete = changedEntries.filter((e) => e.status === "D").map((e) => e.file)
      const oldRenamedFiles = changedEntries
        .filter((e) => e.status === "R" && e.oldFile)
        .map((e) => e.oldFile!)

      // Archive changed files to /tmp using tar (one command, preserves directory structure)
      if (filesToCopy.length > 0) {
        await sandbox.files.write("/tmp/tweaky-filelist.txt", filesToCopy.join("\n"))
        await sandbox.commands.run(
          `cd ${appDir} && tar cf /tmp/tweaky-files.tar -T /tmp/tweaky-filelist.txt`,
          { timeoutMs: 30_000 },
        )
      }

      // Write delete list to file (avoids shell injection from filenames with $, backticks, etc.)
      const allDeletes = [...filesToDelete, ...oldRenamedFiles]
      if (allDeletes.length > 0) {
        await sandbox.files.write("/tmp/tweaky-deletes.txt", allDeletes.join("\n"))
      }

      // Add GitHub remote with token auth
      const remoteUrl = `https://x-access-token:${githubToken}@github.com/${owner}/${repo}.git`
      const remoteResult = await sandbox.git.remoteAdd(appDir, "origin", remoteUrl, {
        overwrite: true,
        timeoutMs: 10_000,
      })
      if (remoteResult.exitCode !== 0) {
        console.error("[sandbox/submit] git remote add failed:", remoteResult.stderr)
        return corsResponse({ error: "Failed to configure git remote" }, { status: 500 })
      }

      // Fetch the default branch
      try {
        await sandbox.commands.run(
          `cd ${appDir} && git fetch origin ${defaultBranch}`,
          { timeoutMs: 60_000 },
        )
      } catch (e) {
        console.error("[sandbox/submit] git fetch failed:", e)
        return corsResponse({ error: "Failed to fetch from GitHub repository" }, { status: 500 })
      }

      // Reset staged changes, checkout upstream branch, restore files — compound command
      const restoreParts = [
        `cd ${appDir}`,
        `git reset HEAD`,
        `git checkout -f -b ${branchName} origin/${defaultBranch}`,
      ]
      if (filesToCopy.length > 0) {
        restoreParts.push(`tar xf /tmp/tweaky-files.tar`)
      }
      if (allDeletes.length > 0) {
        restoreParts.push(`xargs -d '\\n' rm -f < /tmp/tweaky-deletes.txt`)
      }
      await sandbox.commands.run(restoreParts.join(" && "), { timeoutMs: 30_000 })

      // Stage restored files and check if there's anything to commit
      let hasChanges = false
      try {
        const stageResult = await sandbox.commands.run(
          `cd ${appDir} && git add -A && git status --porcelain`,
          { timeoutMs: 30_000 },
        )
        hasChanges = stageResult.stdout.trim().length > 0
      } catch (e) {
        console.error("[sandbox/submit] git add/status failed:", e)
        return corsResponse({ error: "Failed to stage changes" }, { status: 500 })
      }

      if (!hasChanges) {
        return corsResponse(
          { error: "No meaningful changes to submit (files matched the current codebase)" },
          { status: 400 },
        )
      }

      // Commit
      const commitResult = await sandbox.git.commit(appDir, commitMessage, {
        authorName: "Tweaky",
        authorEmail: "bot@tweaky.dev",
        timeoutMs: 30_000,
      })
      if (commitResult.exitCode !== 0) {
        console.error("[sandbox/submit] git commit failed:", commitResult.stderr)
        return corsResponse({ error: "Failed to commit changes" }, { status: 500 })
      }

      // Push
      const pushResult = await sandbox.git.push(appDir, {
        remote: "origin",
        branch: branchName,
        username: "x-access-token",
        password: githubToken,
        timeoutMs: 60_000,
      })
      if (pushResult.exitCode !== 0) {
        console.error("[sandbox/submit] git push failed:", pushResult.stderr)
        return corsResponse({ error: "Failed to push changes to GitHub" }, { status: 500 })
      }
    } catch (e) {
      console.error("[sandbox/submit] Git operations failed:", e)
      const msg = e instanceof Error ? e.message : String(e)
      return corsResponse({ error: `Failed to push changes: ${msg}` }, { status: 500 })
    }

    // Create the PR
    try {
      // Build a concise change summary (no raw diff — it can exceed GitHub's 65536 char limit)
      const changeSummary = changedEntries
        .map((e) => {
          const prefix = e.status === "A" ? "+" : e.status === "D" ? "-" : e.status === "R" ? "→" : "M"
          return `${prefix} ${e.file}`
        })
        .join("\n")

      const octokit = new Octokit({ auth: githubToken })
      const { data: pr } = await octokit.pulls.create({
        owner, repo,
        title: `[Tweaky] ${prompt}`,
        head: branchName,
        base: defaultBranch,
        body: `## Tweaky Submission

**Request:** ${prompt}
**Submitted by:** ${userEmail}
**Requested bounty:** ${bountyAmount} points

### Changed files

\`\`\`
${changeSummary}
\`\`\`

---
*Generated by [Tweaky](https://tweaky.dev)*`,
      })

      // DB insert is best-effort — don't fail the request if it errors
      try {
        await getSupabaseAdmin().from("submissions").insert({
          project_id: project.id,
          user_prompt: prompt,
          user_email: userEmail,
          bounty_amount: bountyAmount,
          pr_url: pr.html_url,
          pr_number: pr.number,
          status: "pending",
        })
      } catch (dbErr) {
        console.error("[sandbox/submit] Supabase insert failed (PR was created):", dbErr)
      }

      await sandbox.kill()

      return corsResponse({ prUrl: pr.html_url })
    } catch (e) {
      console.error("[sandbox/submit] GitHub PR creation failed:", e)
      const msg = e instanceof Error ? e.message : String(e)
      return corsResponse(
        { error: `Failed to create PR on GitHub: ${msg.slice(-300)}` },
        { status: 500 },
      )
    }
  } catch (error) {
    console.error("[sandbox/submit] Error:", error)
    if (sandbox) {
      try { await sandbox.kill() } catch { /* best effort */ }
    }
    return corsResponse(
      { error: error instanceof Error ? error.message : "Internal server error" },
      { status: 500 },
    )
  }
}
